Repository SonarOpenCommunity/sonar-cxx, pull requests merged in 2018-10, with the labels that each got.

#1558 Update clang-tidy rules; Tune severities
  cxx-sensors/src/main/resources/clangtidy.xml
  cxx-sensors/src/tools/clangtidy_createrules.py
Labels: enhancement

#1562 nestedNameSpecifier test
  cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java
  cxx-squid/src/test/java/org/sonar/cxx/parser/ExpressionTest.java
Labels: enhancement

#1564 cppcheck.xml fix name and description of unmatchedSuppression
  cxx-sensors/src/main/resources/cppcheck.xml
Labels: bug

#1565 make CxxParseErrorLoggerVisitor less verbose
  cxx-sensors/src/main/java/org/sonar/cxx/postjobs/FinalReport.java
  cxx-sensors/src/test/java/org/sonar/cxx/postjobs/FinalReportTest.java
  cxx-sensors/src/test/resources/org/sonar/cxx/postjobs/syntaxerror.cc
  cxx-squid/src/main/java/org/sonar/cxx/visitors/CxxParseErrorLoggerVisitor.java
  cxx-squid/src/test/java/org/sonar/cxx/visitors/CxxParseErrorLoggerVisitorTest.java
  sonar-c-plugin/src/main/java/org/sonar/plugins/c/CPlugin.java
  sonar-c-plugin/src/test/java/org/sonar/plugins/c/CPluginTest.java
  sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxPlugin.java
  sonar-cxx-plugin/src/test/java/org/sonar/plugins/cxx/CxxPluginTest.java
Labels: enhancement

#1559 Fix MethodName for nested classes
  cxx-checks/src/main/java/org/sonar/cxx/checks/naming/MethodNameCheck.java
  cxx-checks/src/test/java/org/sonar/cxx/checks/naming/MethodNameCheckTest.java
  cxx-checks/src/test/resources/checks/MethodName.cc
Labels: bug

#1566 Update clang-tidy rules; Add clang diagnostics
  cxx-sensors/src/main/resources/clangtidy.xml
  cxx-sensors/src/test/java/org/sonar/cxx/sensors/clangtidy/CxxClangTidyRuleRepositoryTest.java
  cxx-sensors/src/tools/clangtidy_createrules.py
Labels: enhancement

#1576 support cppcheck 1.85
  cxx-sensors/src/main/resources/cppcheck.xml
  cxx-sensors/src/test/java/org/sonar/cxx/sensors/cppcheck/CxxCppCheckRuleRepositoryTest.java
Labels: enhancement

#1568 make all sensors 'reportPath' properties multi-value
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/squid/CxxSquidSensor.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxReportSensor.java
  cxx-sensors/src/test/java/org/sonar/cxx/sensors/coverage/CxxCoberturaSensorTest.java
  sonar-c-plugin/src/main/java/org/sonar/plugins/c/CPlugin.java
  sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxPlugin.java
  sonar-cxx-plugin/src/test/java/org/sonar/plugins/cxx/CxxPluginTest.java
Labels: enhancement

#1567 make missing include less verbose
  cxx-sensors/src/main/java/org/sonar/cxx/postjobs/FinalReport.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/squid/CxxSquidSensor.java
  cxx-sensors/src/test/java/org/sonar/cxx/postjobs/FinalReportTest.java
  cxx-sensors/src/test/resources/org/sonar/cxx/postjobs/syntaxerror.cc
  cxx-squid/src/main/java/org/sonar/cxx/CxxConfiguration.java
  cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java
  cxx-squid/src/main/java/org/sonar/cxx/visitors/CxxParseErrorLoggerVisitor.java
  sonar-c-plugin/src/main/java/org/sonar/plugins/c/CPlugin.java
  sonar-c-plugin/src/test/java/org/sonar/plugins/c/CPluginTest.java
  sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxPlugin.java
  sonar-cxx-plugin/src/test/java/org/sonar/plugins/cxx/CxxPluginTest.java
Labels: enhancement

#1572 Alternative operator representations
  cxx-squid/src/main/java/org/sonar/cxx/api/CppPunctuator.java
  cxx-squid/src/main/java/org/sonar/cxx/api/CxxKeyword.java
  cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java
Labels: bug

#1575 path normalization / absolutization is not allowed to use File::getCanonicalPath()
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/BullseyeParser.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CoberturaParser.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CoverageParser.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/TestwellCtcTxtParser.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/VisualStudioParser.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxIssuesReportSensor.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxUtils.java
Labels: bug

#1577 Complete support of alternative operators
  cxx-squid/src/main/java/org/sonar/cxx/CxxComplexityConstants.java
  cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java
  cxx-squid/src/main/java/org/sonar/cxx/visitors/AbstractCxxPublicApiVisitor.java
  cxx-squid/src/main/java/org/sonar/cxx/visitors/CxxComplexitySource.java
  cxx-squid/src/test/java/org/sonar/cxx/CxxAstScannerTest.java
  cxx-squid/src/test/java/org/sonar/cxx/parser/ExpressionTest.java
  cxx-squid/src/test/java/org/sonar/cxx/parser/OverloadingTest.java
  cxx-squid/src/test/java/org/sonar/cxx/visitors/CxxCognitiveComplexityVisitorTest.java
  cxx-squid/src/test/resources/metrics/complexity_alternative.cc
  cxx-squid/src/test/resources/visitors/binary_logical_mixed_alternative.cc
Labels: bug

#1580 Public API: ignore methods outside of class
  cxx-squid/src/main/java/org/sonar/cxx/visitors/AbstractCxxPublicApiVisitor.java
  cxx-squid/src/main/java/org/sonar/cxx/visitors/CxxPublicApiVisitor.java
  cxx-squid/src/test/java/org/sonar/cxx/visitors/CxxPublicApiVisitorTest.java
  cxx-squid/src/test/resources/metrics/public_api.h
  cxx-squid/src/test/resources/metrics/template.h
  sonar-c-plugin/src/main/resources/org/sonar/l10n/c/rules/c/UndocumentedApi.html
  sonar-cxx-plugin/src/main/resources/org/sonar/l10n/c++/rules/cxx/UndocumentedApi.html
Labels: bug, enhancement

#1581 add SQ7.4 for testing
  .travis.yml
Labels: enhancement

#1582 test sonar-scanner-cli-3.2.0.1227
  .travis.yml
  appveyor.yml
Labels: enhancement
