Repository SonarOpenCommunity/sonar-cxx, pull requests merged in 2019-04, with the labels that each got.

#1701 support real paths in coverage sensor for C++/CLI
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/other/CxxOtherSensor.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/CxxXunitSensor.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxIssuesReportSensor.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxReportSensor.java
  cxx-sensors/src/test/java/org/sonar/cxx/sensors/utils/CxxReportSensorTest.java
Labels: bug

#1709 support OpenCppCoverage Corbertura file format
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CoberturaParser.java
  cxx-sensors/src/test/java/org/sonar/cxx/sensors/coverage/CxxCoberturaSensorTest.java
Labels: bug, enhancement

#1705 seperate cxx-lint tool
  appveyor.yml
  sonar-cxx-plugin/pom.xml
Labels: enhancement

#1710 Add path/flow support for Clang Static Analyzer *.plist reports
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/clangsa/CxxClangSASensor.java
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxIssuesReportSensor.java
  cxx-sensors/src/test/java/org/sonar/cxx/sensors/clangsa/CxxClangSASensorTest.java
  cxx-squid/src/main/java/org/sonar/cxx/utils/CxxReportIssue.java
  cxx-squid/src/test/java/org/sonar/cxx/utils/CxxReportIssueTest.java
  pom.xml
Labels: enhancement

#1708 fix gcc warnings without rule id
  cxx-sensors/src/main/java/org/sonar/cxx/sensors/compiler/gcc/CxxCompilerGccSensor.java
  cxx-sensors/src/main/resources/compiler-gcc.xml
  cxx-sensors/src/test/java/org/sonar/cxx/sensors/compiler/gcc/CxxCompilerGccSensorTest.java
  cxx-sensors/src/test/resources/org/sonar/cxx/sensors/reports-project/compiler-reports/build-warning-without-id.gcclog
Labels: enhancement
